version: '2'

services:
    {{cookiecutter.project_slug}}:
        build:
          context: .
        image: {{cookiecutter.project_slug }}:latest
        container_name: {{cookiecutter.project_slug }}
        ports:
          - "5000:5000"
        volumes:
         - .:/opt/{{cookiecutter.project_slug}}
