swagger: '2.0'
info:
  title: {{cookiecutter.project_name}}
  version: {{cookiecutter.version}}

paths:
  /:
    get:
      x-swagger-router-controller: controllers
      operationId: hello_world
      parameters:
        - name: message
          description: Some message.
          in: query
          type: string
          required: true
      responses:
        "200":
          description: Just some text
          schema:
            type: string
